; ============================================================================
; TickOS Stage 2 — Tick-Stream Machine Interpreter
; Sectors 2-5, loaded at 0x7E00.  2048 bytes.
;
; THE CMOS PERSISTENCE PROOF:
;
;   First boot (USB inserted):
;     - Writes a program into CMOS battery: LDA 14, OUT, LDA 15, OUT, HLT
;     - Writes data: CMOS[0x14]='O', CMOS[0x15]='K'
;     - Shows: "FIRST BOOT - Writing program to CMOS..."
;     - Executes the program from CMOS bits → prints "OK"
;
;   Second boot (USB still inserted, or replugged after reboot):
;     - Finds the program already in CMOS battery!
;     - Shows: "PROGRAM FOUND IN CMOS! (survived power-off)"
;     - Executes the same program → prints "OK"
;
;   The "OK" on screen was generated by code living in the CMOS battery.
;   The USB only provides the interpreter. The program is in the battery.
;
; DISPLAY: All output at FIXED screen positions. Nothing scrolls.
;   Row 0:    Title bar (blue)
;   Row 2:    CMOS status (first boot vs found)
;   Row 4:    Live tick status (counter, buffer, phase, registers)
;   Row 6-10: Instruction decode log (each instruction appears here)
;   Row 12:   Output header
;   Row 14:   *** THE OUTPUT: "OK" appears here in big green ***
;   Row 17+:  Completion messages (after HLT)
;
; Build:  nasm -f bin stage2.asm -o stage2.bin
; ============================================================================

[bits 16]
[org 0x7E00]

entry:
    cli
    xor  ax, ax
    mov  ds, ax
    mov  es, ax
    mov  ss, ax
    mov  sp, 0x7BF0

    ; ── Video mode 3: 80x25 colour text (clears screen) ───────────────
    mov  ax, 0x0003
    int  0x10

    ; ── Hide hardware cursor ──────────────────────────────────────────
    mov  ah, 0x01
    mov  cx, 0x2000
    int  0x10

    ; ── Draw static screen layout ─────────────────────────────────────
    call draw_ui

    ; ── Zero interpreter state ────────────────────────────────────────
    xor  ax, ax
    mov  [bbuf], al
    mov  [bpos], al
    mov  [phase], al
    mov  [cur_op], al
    mov  [cur_adr], al
    mov  [rega], al
    mov  [regb], al
    mov  [halted], al
    mov  [outcol], al
    mov  [icnt], al
    mov  [bitptr], ax
    mov  [tickcnt], ax

    ; ══════════════════════════════════════════════════════════════════
    ; CHECK CMOS: does our program already exist?
    ; We use CMOS[0x13] as a signature byte. 0xBB = program present.
    ; ══════════════════════════════════════════════════════════════════
    mov  al, 0x13
    out  0x70, al
    in   al, 0x71
    cmp  al, 0xBB
    je   .found

    ; ── FIRST BOOT: Write program to CMOS battery ─────────────────────
    call write_cmos_program

    ; Show "FIRST BOOT" message at row 2 (yellow)
    mov  ax, 0xB800
    mov  es, ax
    mov  di, (2*80+2)*2
    mov  si, str_first
    mov  ah, 0x0E             ; yellow on black
    call vs
    xor  ax, ax
    mov  es, ax
    jmp  .go

.found:
    ; ── PROGRAM FOUND: It survived in the battery! ────────────────────
    mov  ax, 0xB800
    mov  es, ax
    mov  di, (2*80+2)*2
    mov  si, str_found
    mov  ah, 0x0A             ; GREEN — this is the proof!
    call vs
    xor  ax, ax
    mov  es, ax

.go:
    ; ══════════════════════════════════════════════════════════════════
    ; PROGRAM RTC: 8 Hz periodic interrupts
    ; ══════════════════════════════════════════════════════════════════

    ; Register A: DV=010 (32.768 kHz osc), RS=1101 (8 Hz)
    mov  al, 0x8A
    out  0x70, al
    mov  al, 0x2D             ; 0010_1101
    out  0x71, al

    ; Register B: enable PIE (bit 6)
    mov  al, 0x8B
    out  0x70, al
    in   al, 0x71
    or   al, 0x40
    mov  cl, al
    mov  al, 0x8B
    out  0x70, al
    mov  al, cl
    out  0x71, al

    ; Read Register C to clear pending
    mov  al, 0x8C
    out  0x70, al
    in   al, 0x71

    ; ── Install IRQ8 handler ──────────────────────────────────────────
    mov  word [0x01C0], irq8
    mov  word [0x01C2], 0x0000

    ; ── Unmask IRQ8 on PIC ────────────────────────────────────────────
    in   al, 0xA1
    and  al, 0xFE             ; unmask IRQ8 on slave
    out  0xA1, al
    in   al, 0x21
    and  al, 0xFB             ; unmask cascade on master
    out  0x21, al

    ; ── GO ────────────────────────────────────────────────────────────
    sti

.idle:
    hlt
    jmp  .idle


; ══════════════════════════════════════════════════════════════════════════
; WRITE_CMOS_PROGRAM — Store "OK" program into CMOS battery
; ══════════════════════════════════════════════════════════════════════════
;
; Program:  LDA 14, OUT, LDA 15, OUT, HLT
; Bits:     0001 010100 1001 0001 010101 1001 1111
;
; CMOS[0x30] = 0x15   (00010101)
; CMOS[0x31] = 0x24   (00100100)
; CMOS[0x32] = 0x55   (01010101)
; CMOS[0x33] = 0x9F   (10011111)
; CMOS[0x34..0x3F] = 0x00
;
; Data:
; CMOS[0x14] = 'O' (0x4F)
; CMOS[0x15] = 'K' (0x4B)
;
write_cmos_program:
    ; Data bytes
    mov  al, 0x14
    out  0x70, al
    mov  al, 0x4F             ; 'O'
    out  0x71, al

    mov  al, 0x15
    out  0x70, al
    mov  al, 0x4B             ; 'K'
    out  0x71, al

    ; Program bytes
    mov  al, 0x30
    out  0x70, al
    mov  al, 0x15
    out  0x71, al

    mov  al, 0x31
    out  0x70, al
    mov  al, 0x24
    out  0x71, al

    mov  al, 0x32
    out  0x70, al
    mov  al, 0x55
    out  0x71, al

    mov  al, 0x33
    out  0x70, al
    mov  al, 0x9F
    out  0x71, al

    ; Zero the rest of program page
    mov  bl, 0x34
.zl: mov  al, bl
     out  0x70, al
     xor  al, al
     out  0x71, al
     inc  bl
     cmp  bl, 0x40
     jl   .zl

    ; Signature: CMOS[0x13] = 0xBB (marks "program present")
    mov  al, 0x13
    out  0x70, al
    mov  al, 0xBB
    out  0x71, al

    ret


; ══════════════════════════════════════════════════════════════════════════
; IRQ8 HANDLER — One tick of the Tick-Stream Machine
; ══════════════════════════════════════════════════════════════════════════
irq8:
    pusha
    push ds
    push es
    xor  ax, ax
    mov  ds, ax

    ; MUST read Register C to acknowledge RTC interrupt
    mov  al, 0x8C
    out  0x70, al
    in   al, 0x71

    ; If halted, skip everything
    cmp  byte [halted], 1
    je   .eoi

    ; Increment tick counter
    inc  word [tickcnt]

    ; ── Read one bit from CMOS program page ────────────────────────────
    ; Bit position [bitptr] → CMOS byte 0x30 + (bitptr/8)
    ; Within byte: MSB-first → bit index = 7 - (bitptr % 8)
    mov  ax, [bitptr]

    ; Byte address: 0x30 + (ax >> 3) & 0x0F
    mov  bx, ax
    shr  bx, 3
    and  bx, 0x0F
    add  bl, 0x30

    ; Bit position within byte: 7 - (ax & 7)
    mov  cx, ax
    and  cl, 7
    mov  ch, 7
    sub  ch, cl
    mov  cl, ch

    ; Read CMOS byte
    mov  al, bl
    out  0x70, al
    in   al, 0x71

    ; Extract single bit
    shr  al, cl
    and  al, 1

    ; Advance bit pointer (wrap at 128)
    inc  word [bitptr]
    cmp  word [bitptr], 128
    jl   .nowrap
    mov  word [bitptr], 0
.nowrap:

    ; ── Show live status at row 4 ──────────────────────────────────────
    push ax                   ; save the bit
    call show_status
    pop  ax                   ; restore the bit

    ; ── Accumulate bit: bbuf = (bbuf << 1) | bit ──────────────────────
    mov  cl, [bbuf]
    shl  cl, 1
    or   cl, al
    mov  [bbuf], cl
    inc  byte [bpos]

    ; ── State machine ──────────────────────────────────────────────────
    cmp  byte [phase], 1
    je   .ph_addr
    cmp  byte [phase], 2
    je   .ph_off

    ; ── Phase 0: collecting 4-bit opcode ───────────────────────────────
    cmp  byte [bpos], 4
    jl   .eoi                 ; need more bits

    ; Got complete opcode
    mov  al, [bbuf]
    and  al, 0x0F
    mov  [cur_op], al
    mov  byte [bbuf], 0
    mov  byte [bpos], 0

    ; Needs operand?
    cmp  al, 1                ; LDA
    je   .go_addr
    cmp  al, 2                ; STA
    je   .go_addr
    cmp  al, 3                ; LDB
    je   .go_addr
    cmp  al, 4                ; STB
    je   .go_addr
    cmp  al, 8                ; JZ
    je   .go_off

    ; Immediate: execute now
    call exec_imm
    jmp  .eoi

.go_addr:
    mov  byte [phase], 1
    jmp  .eoi
.go_off:
    mov  byte [phase], 2
    jmp  .eoi

    ; ── Phase 1: collecting 6-bit address ──────────────────────────────
.ph_addr:
    cmp  byte [bpos], 6
    jl   .eoi
    mov  al, [bbuf]
    and  al, 0x3F
    mov  [cur_adr], al
    mov  byte [bbuf], 0
    mov  byte [bpos], 0
    mov  byte [phase], 0
    call exec_addr
    jmp  .eoi

    ; ── Phase 2: collecting 4-bit JZ offset ────────────────────────────
.ph_off:
    cmp  byte [bpos], 4
    jl   .eoi
    mov  byte [bbuf], 0
    mov  byte [bpos], 0
    mov  byte [phase], 0
    ; JZ not used in OK demo, just log it
    call log_instr
    jmp  .eoi

.eoi:
    mov  al, 0x20
    out  0xA0, al             ; EOI slave PIC
    out  0x20, al             ; EOI master PIC
    pop  es
    pop  ds
    popa
    iret


; ══════════════════════════════════════════════════════════════════════════
; EXECUTE IMMEDIATE (no operand)
; ══════════════════════════════════════════════════════════════════════════
exec_imm:
    call log_instr

    mov  al, [cur_op]

    cmp  al, 5                ; ADD
    je   .add
    cmp  al, 6                ; INCA
    je   .inca
    cmp  al, 7                ; DECA
    je   .deca
    cmp  al, 9                ; OUT
    je   .out
    cmp  al, 0x0B             ; XOR
    je   .xor
    cmp  al, 0x0E             ; SWAP
    je   .swap
    cmp  al, 0x0F             ; HLT
    je   .hlt
    ret                       ; NOP or unknown

.add:
    mov  al, [rega]
    add  al, [regb]
    mov  [rega], al
    ret
.inca:
    inc  byte [rega]
    ret
.deca:
    dec  byte [rega]
    ret
.out:
    mov  al, [rega]
    call output_char
    ret
.xor:
    mov  al, [rega]
    xor  al, [regb]
    mov  [rega], al
    ret
.swap:
    mov  al, [rega]
    xchg al, [regb]
    mov  [rega], al
    ret
.hlt:
    mov  byte [halted], 1
    call show_done
    ret


; ══════════════════════════════════════════════════════════════════════════
; EXECUTE WITH ADDRESS (LDA, STA, LDB, STB)
; ══════════════════════════════════════════════════════════════════════════
exec_addr:
    call log_instr

    mov  al, [cur_op]
    cmp  al, 2
    je   .sta
    cmp  al, 3
    je   .ldb
    cmp  al, 4
    je   .stb

    ; LDA: A = CMOS[addr]
    mov  al, [cur_adr]
    and  al, 0x3F
    out  0x70, al
    in   al, 0x71
    mov  [rega], al
    ret

.sta:
    mov  al, [cur_adr]
    and  al, 0x3F
    out  0x70, al
    mov  al, [rega]
    out  0x71, al
    ret

.ldb:
    mov  al, [cur_adr]
    and  al, 0x3F
    out  0x70, al
    in   al, 0x71
    mov  [regb], al
    ret

.stb:
    mov  al, [cur_adr]
    and  al, 0x3F
    out  0x70, al
    mov  al, [regb]
    out  0x71, al
    ret


; ══════════════════════════════════════════════════════════════════════════
; DISPLAY: Draw the static screen layout (called once)
; ══════════════════════════════════════════════════════════════════════════
draw_ui:
    push es
    mov  ax, 0xB800
    mov  es, ax

    ; Row 0: blue title bar
    xor  di, di
    mov  cx, 80
    mov  ax, 0x1F20           ; white-on-blue space
    rep  stosw

    mov  di, 4                ; col 2
    mov  si, str_title
    mov  ah, 0x1E             ; yellow on blue
    call vs

    ; Row 6: instruction log header
    mov  di, (6*80+2)*2
    mov  si, str_decode
    mov  ah, 0x07
    call vs

    ; Row 12: output section header
    mov  di, (12*80+2)*2
    mov  si, str_output
    mov  ah, 0x0F
    call vs

    ; Row 13: top border line
    mov  di, (13*80+2)*2
    mov  cx, 40
    mov  ah, 0x0F
    mov  al, 0xC4
    rep  stosw

    ; Row 15: bottom border line
    mov  di, (15*80+2)*2
    mov  cx, 40
    mov  ah, 0x0F
    mov  al, 0xC4
    rep  stosw

    pop  es
    ret


; ══════════════════════════════════════════════════════════════════════════
; DISPLAY: Live status at row 4 (updated every tick)
; ══════════════════════════════════════════════════════════════════════════
show_status:
    push es
    mov  ax, 0xB800
    mov  es, ax

    ; "Tick:XXXX" at col 2
    mov  di, (4*80+2)*2
    mov  si, str_tick
    mov  ah, 0x08
    call vs
    mov  ax, [tickcnt]
    call vhex16

    ; "Buf:XX" at col 16
    mov  di, (4*80+16)*2
    mov  si, str_buf
    mov  ah, 0x08
    call vs
    mov  al, [bbuf]
    call vhex8

    ; "Ph:X" at col 27
    mov  di, (4*80+27)*2
    mov  si, str_ph
    mov  ah, 0x08
    call vs
    mov  al, [phase]
    add  al, '0'
    mov  ah, 0x08
    stosw

    ; Spinner at col 35
    mov  di, (4*80+35)*2
    mov  ax, [tickcnt]
    and  ax, 3
    mov  bx, ax
    add  bx, spin
    mov  al, [bx]
    mov  ah, 0x0E
    stosw

    ; "A:XX B:XX" at col 40
    mov  di, (4*80+40)*2
    mov  al, 'A'
    mov  ah, 0x0B
    stosw
    mov  al, ':'
    stosw
    mov  al, [rega]
    call vhex8
    mov  al, ' '
    mov  ah, 0x08
    stosw
    mov  al, 'B'
    mov  ah, 0x0B
    stosw
    mov  al, ':'
    stosw
    mov  al, [regb]
    call vhex8

    pop  es
    ret

spin db '|/-\'


; ══════════════════════════════════════════════════════════════════════════
; DISPLAY: Log a decoded instruction at rows 7-11
; ══════════════════════════════════════════════════════════════════════════
log_instr:
    push es
    push di
    push bx
    push cx

    mov  ax, 0xB800
    mov  es, ax

    ; Row = 7 + icnt (max 5 rows)
    xor  ax, ax
    mov  al, [icnt]
    cmp  al, 5
    jge  .done

    add  al, 7
    mov  bl, 80
    mul  bl
    add  ax, 4                ; col 2
    shl  ax, 1
    mov  di, ax

    ; Print "[n] "
    mov  al, '['
    mov  ah, 0x07
    stosw
    mov  al, [icnt]
    add  al, '1'
    stosw
    mov  al, ']'
    stosw
    mov  al, ' '
    stosw

    ; Print opcode name (4 chars)
    mov  al, [cur_op]
    and  ax, 0x0F
    shl  ax, 2
    add  ax, opnames
    mov  si, ax
    mov  ah, 0x0B             ; cyan
    mov  cx, 4
.nl: lodsb
     stosw
     loop .nl

    ; Print operand details for address-bearing opcodes
    mov  al, [cur_op]
    cmp  al, 1
    je   .show_adr
    cmp  al, 2
    je   .show_adr
    cmp  al, 3
    je   .show_adr
    cmp  al, 4
    je   .show_adr

    ; If OUT, show the character
    cmp  al, 9
    jne  .not_out
    mov  al, ' '
    mov  ah, 0x0B
    stosw
    mov  al, 0x1A             ; →
    mov  ah, 0x08
    stosw
    mov  al, ' '
    stosw
    mov  al, 0x27             ; '
    mov  ah, 0x0A
    stosw
    mov  al, [rega]
    stosw
    mov  al, 0x27
    stosw
    jmp  .done

.not_out:
    ; If HLT
    cmp  al, 0x0F
    jne  .done
    mov  al, ' '
    mov  ah, 0x0C             ; red
    stosw
    mov  si, str_stopped
    call vs
    jmp  .done

.show_adr:
    mov  al, ' '
    mov  ah, 0x0B
    stosw
    mov  al, [cur_adr]
    call vhex8
    mov  al, ' '
    mov  ah, 0x08
    stosw
    mov  al, 0x1A             ; →
    stosw
    mov  al, ' '
    stosw
    ; Show value in register after load
    mov  al, [rega]
    call vhex8
    ; If printable, show character
    mov  al, [rega]
    cmp  al, 0x20
    jl   .done
    cmp  al, 0x7E
    jg   .done
    mov  ah, 0x08
    push ax
    mov  al, ' '
    stosw
    mov  al, '('
    stosw
    pop  ax
    mov  ah, 0x0A             ; green
    stosw
    mov  al, ')'
    mov  ah, 0x08
    stosw

.done:
    inc  byte [icnt]
    pop  cx
    pop  bx
    pop  di
    pop  es
    ret


; ══════════════════════════════════════════════════════════════════════════
; DISPLAY: Print character to the OUTPUT area (row 14, big green)
; ══════════════════════════════════════════════════════════════════════════
output_char:
    push es
    push bx

    mov  bx, 0xB800
    mov  es, bx

    ; Position: row 14, col 10 + outcol*3 (spread out for visibility)
    xor  bh, bh
    mov  bl, [outcol]
    mov  cl, bl
    shl  bx, 1               ; *2
    add  bx, cx              ; *3 total
    shl  bx, 1               ; *2 for word offset
    add  bx, (14*80+10)*2

    ; Write char in bright green, repeated for size
    mov  ah, 0x0A             ; bright green
    mov  [es:bx], al
    mov  [es:bx+1], ah
    mov  [es:bx+2], al
    mov  [es:bx+3], ah

    inc  byte [outcol]

    pop  bx
    pop  es
    ret


; ══════════════════════════════════════════════════════════════════════════
; DISPLAY: Completion messages (after HLT)
; ══════════════════════════════════════════════════════════════════════════
show_done:
    push es
    mov  ax, 0xB800
    mov  es, ax

    mov  di, (17*80+2)*2
    mov  si, str_done1
    mov  ah, 0x0E             ; yellow
    call vs

    mov  di, (18*80+2)*2
    mov  si, str_done2
    mov  ah, 0x0A             ; green
    call vs

    mov  di, (19*80+2)*2
    mov  si, str_done3
    mov  ah, 0x0A
    call vs

    mov  di, (21*80+2)*2
    mov  si, str_done4
    mov  ah, 0x08             ; grey
    call vs

    mov  di, (22*80+2)*2
    mov  si, str_done5
    mov  ah, 0x08
    call vs

    pop  es
    ret


; ══════════════════════════════════════════════════════════════════════════
; VGA HELPERS
; ══════════════════════════════════════════════════════════════════════════

; Write null-terminated string from DS:SI to ES:DI, attribute in AH
vs:
    lodsb
    or   al, al
    jz   .d
    stosw
    jmp  vs
.d: ret

; Write AL as 2 hex digits at ES:DI
vhex8:
    push ax
    shr  al, 4
    call .nib
    pop  ax
    and  al, 0x0F
.nib:
    cmp  al, 10
    jl   .dec
    add  al, 'A'-10
    jmp  .wr
.dec:
    add  al, '0'
.wr:
    mov  ah, 0x0F
    stosw
    ret

; Write AX as 4 hex digits at ES:DI
vhex16:
    push ax
    mov  al, ah
    call vhex8
    pop  ax
    jmp  vhex8


; ══════════════════════════════════════════════════════════════════════════
; OPCODE NAME TABLE (4 chars each, indexed by opcode * 4)
; ══════════════════════════════════════════════════════════════════════════
opnames:
    db 'NOP '    ; 0
    db 'LDA '    ; 1
    db 'STA '    ; 2
    db 'LDB '    ; 3
    db 'STB '    ; 4
    db 'ADD '    ; 5
    db 'INCA'    ; 6
    db 'DECA'    ; 7
    db 'JZ  '    ; 8
    db 'OUT '    ; 9
    db 'INP '    ; A
    db 'XOR '    ; B
    db 'SHL '    ; C
    db 'SHR '    ; D
    db 'SWAP'    ; E
    db 'HLT '    ; F


; ══════════════════════════════════════════════════════════════════════════
; STRINGS
; ══════════════════════════════════════════════════════════════════════════
str_title   db ' TickOS v1.0 - CMOS Battery Computer', 0
str_first   db 'FIRST BOOT: Writing program to CMOS battery...', 0
str_found   db 'PROGRAM FOUND IN CMOS! (survived power cycle)', 0
str_tick    db 'Tick:', 0
str_buf     db 'Buf:', 0
str_ph      db 'Ph:', 0
str_decode  db 'Decoded instructions (from CMOS bits):', 0
str_output  db 'CMOS PROGRAM OUTPUT:', 0
str_stopped db '(stopped)', 0

str_done1   db 'Program executed from CMOS battery!', 0
str_done2   db '"OK" was generated by code in the CMOS chip.', 0
str_done3   db 'This program persists even with power off.', 0
str_done4   db 'Reboot to see "PROGRAM FOUND IN CMOS" message.', 0
str_done5   db 'USB = interpreter. CMOS battery = the program.', 0


; ══════════════════════════════════════════════════════════════════════════
; INTERPRETER STATE
; ══════════════════════════════════════════════════════════════════════════
bbuf     db 0                 ; bit accumulation buffer
bpos     db 0                 ; bits collected so far
phase    db 0                 ; 0=opcode, 1=addr, 2=offset
cur_op   db 0                 ; current opcode
cur_adr  db 0                 ; current 6-bit address
rega     db 0                 ; register A
regb     db 0                 ; register B
halted   db 0                 ; 1 = program halted
outcol   db 0                 ; output cursor column
icnt     db 0                 ; instructions logged so far
bitptr   dw 0                 ; current bit position in CMOS
tickcnt  dw 0                 ; tick counter


; ══════════════════════════════════════════════════════════════════════════
; PAD TO EXACTLY 2048 BYTES (4 sectors)
; ══════════════════════════════════════════════════════════════════════════
times 2048 - ($ - $$) db 0
